AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  powertools-quickstart

  Sample SAM Template for powertools-quickstart

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    # Environment:
    #   Variables:
    #     QUEUE_URL: https://sqs.us-east-1.amazonaws.com/748887400437/InvokeQueue.fifo


Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'POST,GET,OPTIONS'"
        AllowHeaders: "'*'"
        AllowOrigin: "'https://daitergg.github.io'"
        MaxAge: "'600'"
  RequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: app.lambda_handler
      Runtime: python3.14
      Architectures:
        - x86_64
      Events:
        RequestEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /request
            Method: post

Outputs:
  ReleaseSonarApi:
    Description: "API Gateway endpoint URL for Prod stage for Request function"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/request/"
  ReleaseSonarFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt RequestFunction.Arn
  RequestFunctionIamRole:
    Description: "Implicit IAM Role created for request function"
    Value: !GetAtt RequestFunctionRole.Arn
