AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  powertools-quickstart

  Sample SAM Template for powertools-quickstart

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3


Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowOrigins: "*"
        AllowHeaders: ['Content-Type']
        AllowMethods: ['GET', 'POST', 'OPTIONS']
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: app.cors_handler
      Runtime: python3.14
      Architectures:
        - x86_64
      Events:
        Cors:
          Type: Api
          Properties:
            Path: /request
            Method: OPTIONS
        HelloWorld:
          Type: Api
          Properties:
            Path: /request
            Method: POST

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/hello/"
  HelloWorldFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  RequestFunctionIamRole:
    Description: "Implicit IAM Role created for request function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
